config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  get '/signup' => 'users#signup'
  post '/users' => 'users#create'
  put '/users/:id' => 'users#update'
  get '/edit' => 'users#edit'

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def query
	end
	def search
		puts params
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users=User.all
	end
	def signup
		@user = User.new
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@id = params[:id]
		# puts "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5"
		# puts @id
		@user = User.find(@id)
		# puts @user.id
		@user.update(params[:user])
		redirect_to root_path
	end
	def create
		User.create(params[:user])
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FormControler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>January Fifth</h1>
<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h2>Edit</h2>

<%= form_for @user ,html: {method: :put} do |f| %>
	<%=f.label :username %>
	<%=f.text_field :username %>
	<%=f.label :favnum %>
	<%=f.text_field :favnum %>
	<%=f.submit :update %>
<% end %>

app/views/users/index.html.erb
<%= link_to "link text...", signup_path() %>
<br>
<% @users.each do |u| %>
	<%= link_to "Edit", edit_user_path(u.id) %>
	<% for i in 1..u.favnum do %>
		<%= u.username %> 
	<% end %>
	<br>
<% end %>

app/views/users/signup.html.erb
<h2>Sign up</h2>

<%= form_for @user do |f| %>
	<%=f.label :username %>
	<%=f.text_field :username %>
	<%=f.label :favnum %>
	<%=f.text_field :favnum %>
	<%=f.submit :create %>
<% end %>